"""description added into items table

Revision ID: 054738db3264
Revises: c4e04d46db8c
Create Date: 2025-09-29 15:19:30.348174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054738db3264'
down_revision = 'c4e04d46db8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
